### ISSUE TITLE
Content Review

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/guides#6]
I’m looking at our shared developer docs and am seeing some content that has gotten a bit stale. This ticket will serve as a list of all pages in this repository and as they get reviewed / updated we will check them off.

- [ ] a11y (Matt)
- [ ] docker
- [x] exception monitoring
- [ ] github
- [x] heroku (Jeremy)
- [x] incident response (Jeremy)
- [x] logging
- [x] ~new relic~
- [x] oauth (Jeremy)
- [ ] pantheon (Matt)
- [x] proxy urls (Jeremy)
- [ ] python
- [x] rails (Jeremy)
- [ ] readme (main index page) (Jeremy)
- [ ] ssl
- [x] touchstone / saml (Jeremy)
- [ ] wordpress (Matt)

Please comment below on any pages you'll be reviewing so others don't duplicate the effort.

**Comment by cabutlermit** [comment]
both the logging and the exception monitoring pages were recently updated.

**Comment by JPrevost** [comment]
Closing so we can open a new clean ticket for a new round of content review
